name: Build and Deploy

on:
  push:
    branches:
      - main # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Replace Web App URL
        run: |
          sed -i "s|<WEB_APP_URL_PLACEHOLDER>|${{ secrets.WEB_APP_URL }}|g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Change this to the correct directory if needed
